# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 18:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20171015_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_fav',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_followers',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_following',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_tweets',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
