# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20171015_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upload_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
