# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20171016_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='user_id',
        ),
    ]
